select * from ContestGroup
select * from ContestGroups
select * from Contests
select * from EmailTemplates
select * from Equities
select * from EquityUserSetting
select * from Groups
select * from GroupsOwners
select * from Interviews
select * from InterviewUsers
select * from MockDepartments
select * from MockUsers
select * from Schedules
select * from UserSettingEquities
select * from UserSettings